# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
#image: gradle:alpine
image: docker:latest

services:
  - docker:dind
# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - package
  - deploy
  - test
  - code_quality

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  image: gradle:alpine
  stage: build
  script: gradle --build-cache assemble
  #when: manual
  artifacts:
    paths:
    - './build/libs/final_project-0.0.1-SNAPSHOT.jar'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

docker-build:
  stage: package
  script:
    - ls -la && pwd 
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE"
    - docker login -u "$COUPONS_REGISTRY_USER" -p "$COUPONS_REGISTRY_PASSWORD" "registry.hub.docker.com"
    - docker tag $CI_REGISTRY_IMAGE registry.hub.docker.com/smuel770/coupons:latest
    - docker tag $CI_REGISTRY_IMAGE registry.hub.docker.com/smuel770/coupons:$CI_COMMIT_REF_NAME_$CI_JOB_ID
    - docker push registry.hub.docker.com/smuel770/coupons:$CI_COMMIT_REF_NAME_$CI_JOB_ID
    - docker push registry.hub.docker.com/smuel770/coupons:latest
  #when: manual

deploy:
  stage: deploy
  script:
    - ls -la && pwd
    - apk add openssh && chmod 0600 ./gradle/id_rsa
    - ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no smuelservice@35.243.185.205 "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
    - ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no smuelservice@35.243.185.205 "docker pull $CI_REGISTRY_IMAGE"
    - (if ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no smuelservice@35.243.185.205 "docker stop my-app-instance" ; then echo "Stoped"; else echo "Exception container dont exist"; fi);
    - ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no smuelservice@35.243.185.205 "docker run -dit --rm -p 8080:8080 -p 2220:2222 --name my-app-instance $CI_REGISTRY_IMAGE"
    #- ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no sem@35.243.170.169 gcloud container clusters get-credentials app-cluster --zone us-central1-a --project sinuous-axiom-213422
    #- ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no sem@35.243.170.169 "kubectl get pods -o name | grep my-app | xargs kubectl delete"
 

test:
  image: gradle:alpine
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build


code_quality:
  image: docker:stable
  stage: code_quality
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json