# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
#image: gradle:alpine
image: docker:latest

services:
  - docker:dind
# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  couponsVmAdrress: "104.196.156.155"

stages:
  - build
  - package
  - deploy
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  image: gradle:alpine
  stage: build
  script: gradle --build-cache assemble
  #when: manual
  artifacts:
    paths:
    - './build/libs/final_project-0.0.1-SNAPSHOT.jar'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

docker-build:
  stage: package
  script:
    - ls -la && pwd
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE"
  #when: manual

deploy:
  stage: deploy
  script:
    - ls -la && pwd
    - apk add openssh && chmod 0600 ./gradle/id_rsa && echo "$COUPONS_REGISTRY_USER"
    #- ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no sem@35.243.170.169 sudo docker login -u "$COUPONS_REGISTRY_USER" -p "$COUPONS_REGISTRY_PASS" $CI_REGISTRY
    - ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no sem@35.243.170.169 "docker pull $CI_REGISTRY_IMAGE"
    #- ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no sem@35.243.170.169 "docker stop my-app-instance"
    - ssh -i ./gradle/id_rsa -o StrictHostKeyChecking=no sem@35.243.170.169 "docker run -dit --rm -p 8080:8080 -p 2220:2222 --name my-app-instance $CI_REGISTRY_IMAGE"
    #- docker build --pull -t "$CI_REGISTRY_IMAGE" .
    #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

test:
  image: gradle:alpine
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
#---
#image: docker:latest
#services:
#  - docker:dind
#
#variables:
#  DOCKER_DRIVER: overlay
#  SPRING_PROFILES_ACTIVE: gitlab-ci
#
#stages:
#  - build
#  - package
#  - deploy
#
#maven-build:
#  image: maven:3-jdk-8
#  stage: build
#  script: "mvn package -B"
#  artifacts:
#    paths:
#      - target/*.jar
#
#docker-build:
#  stage: package
#  script:
#    - docker build -t registry.gitlab.com/marcolenzo/actuator-sample .
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#    - docker push registry.gitlab.com/marcolenzo/actuator-sample
#---
# This file is a template, and might need editing before it works on your project.
# Official docker image.
#image: docker:latest
#
#services:
#  - docker:dind
#
#before_script:
#  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#
#build-master:
#  stage: build
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#    - docker push "$CI_REGISTRY_IMAGE"
#  only:
#    - master
#
#build:
#  stage: build
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
#    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#  except:
#    - master
